### ISSUE TITLE
fix endpoint naming (to-all-users etc.)

### ISSUE THREAD

**Issue by yahyacan** [yusufyil/Spring-Boot-Fake-Mail-Project#10]
https://github.com/yusufyil/Spring-Boot-Fake-Mail-Project/blob/09e460eddb5295e9d03c016693692d05f9b41a6d/Mail-Producer/src/main/java/io/smartiq/mailproducer/Controller/MailProducerController.java#L22

**Comment by yusufyil** [comment]
changed end point names.
