### ISSUE TITLE
all directory name witouh leaf directory has written with lower case but leaf directory name is starting with upper case. I has be all the same. (.config etc)

### ISSUE THREAD

**Issue by yahyacan** [yusufyil/Spring-Boot-Fake-Mail-Project#12]
https://github.com/yusufyil/Spring-Boot-Fake-Mail-Project/blob/09e460eddb5295e9d03c016693692d05f9b41a6d/Mail-Producer/src/main/java/io/smartiq/mailproducer/Config/KafkaProducerConfig.java#L1

**Comment by yusufyil** [comment]
all package names have been refactored.
