### ISSUE TITLE
this mean is : drop schema when stop app. is it correct with what do you want to do?

### ISSUE THREAD

**Issue by yahyacan** [yusufyil/Spring-Boot-Fake-Mail-Project#15]
https://github.com/yusufyil/Spring-Boot-Fake-Mail-Project/blob/09e460eddb5295e9d03c016693692d05f9b41a6d/src/main/resources/application.properties#L5

**Comment by yusufyil** [comment]
I set create-drop on purpose. Instead of updating every time i start app, I save fresh records to database via command line runner at SpringFakeMailApplication class.
