### ISSUE TITLE
you dont have a method for find mail list by a user email.

### ISSUE THREAD

**Issue by yahyacan** [yusufyil/Spring-Boot-Fake-Mail-Project#17]
https://github.com/yusufyil/Spring-Boot-Fake-Mail-Project/blob/09e460eddb5295e9d03c016693692d05f9b41a6d/src/main/java/io/smartiq/springfakemail/Service/Impl/MailServiceImpl.java#L33

**Comment by yusufyil** [comment]
added required methods to both service layer and repository layer in order to get one users all mails.
