### ISSUE TITLE
you are caching data, but when saving  new data, you didnt evict cache, so actually your cache mechanism is working wrong

### ISSUE THREAD

**Issue by yahyacan** [yusufyil/Spring-Boot-Fake-Mail-Project#18]
https://github.com/yusufyil/Spring-Boot-Fake-Mail-Project/blob/09e460eddb5295e9d03c016693692d05f9b41a6d/src/main/java/io/smartiq/springfakemail/Service/Impl/MailServiceImpl.java#L38

**Comment by yusufyil** [comment]
I made clearCache() method call at controller layer whenever server invokes save, update, delete methods for both mail and user entities.
